from __future__ import annotations

"""
Befehlskatalog (CMD) inkl. Kurzinfos/Tooltips.
"""

from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class CommandSpec:
    """Metadaten eines Rotor-CMDs."""

    name: str
    kind: str = "none"
    params_literal: Optional[str] = None
    min_value: Optional[float] = None
    max_value: Optional[float] = None
    decimals: Optional[int] = None
    step: Optional[float] = None
    default: Optional[float] = None
    help_text: str = ""
    help_text_en: str = ""


SPECS_DATA: list[dict] = [
    {
        "name": "TEST",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Verbindungstest (Ping).",
        "help_text_en": "Connection test (Ping).",
    },
    {
        "name": "STOP",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Weicher Stop (normales Abbremsen). Beendet eine Positionsfahrt. Fehler werden NICHT gelöscht.",
        "help_text_en": "Soft stop (normal braking). Ends a position move. Errors are NOT cleared.",
    },
    {
        "name": "NSTOP",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Not-Stop über RS485. Setzt sofort Fehler SE_NSTOP_CMD und stoppt.",
        "help_text_en": "Emergency stop via RS485. Immediately sets error SE_NSTOP_CMD and stops.",
    },
    {
        "name": "GETREF",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Abfragen, ob Referenz (Homing) vorhanden ist. Antwort: 0 = nicht referenziert, 1 = referenziert.",
        "help_text_en": "Query whether reference (homing) is available. Response: 0 = not homed, 1 = homed.",
    },
    {
        "name": "GETPOSDG",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Aktuelle Position in Grad (0,01°). Rückgabe ist immer die Offset-korrigierte Position.",
        "help_text_en": "Current position in degrees (0.01°). Return value is always the offset-corrected position.",
    },
    {
        "name": "GETIS",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Aktueller Strommesswert (mV) nach Offset-Abzug. Wird passend zur Bewegungsrichtung aus IS1/IS2 gewählt.",
        "help_text_en": "Current measurement value (mV) after offset subtraction. Selected from IS1/IS2 based on direction of movement.",
    },
    {
        "name": "GETTEMPA",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Umgebungstemperatur in °C. DS18B20, 2 Nachkommastellen.",
        "help_text_en": "Ambient temperature in °C. DS18B20, 2 decimal places.",
    },
    {
        "name": "GETTEMPM",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Motortemperatur in °C. Wenn Motor-Sensor deaktiviert: immer 0.",
        "help_text_en": "Motor temperature in °C. If motor sensor disabled: always 0.",
    },
    {
        "name": "SETANEMOOF",
        "kind": "float",
        "min_value": -200.0,
        "max_value": 200.0,
        "decimals": 1,
        "step": 0.1,
        "default": 0.0,
        "help_text": "Offset für Windmesser (km/h) setzen. Empfehlung: -5 bis +5. Hilfreich wenn Sensor bei Windstille nicht 0 zeigt.",
        "help_text_en": "Set wind meter offset (km/h). Recommended: -5 to +5. Helpful if sensor does not show 0 at calm wind.",
    },
    {
        "name": "GETANEMOOF",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Offset der Windgeschwindigkeit (km/h) lesen (1 Nachkommastelle, z.B. -1,5). Wert stammt aus NVS/Preferences Key ano.",
        "help_text_en": "Read wind speed offset (km/h) (1 decimal place, e.g. -1.5). Value from NVS/Preferences key ano.",
    },
    {
        "name": "SETWINDENABLE",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 1.0,
        "decimals": 0,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Windauswertung aktivieren (1) / deaktivieren (0). 0 = aus, 1 = ein. Wird gespeichert.",
        "help_text_en": "Enable (1) / disable (0) wind evaluation. 0 = off, 1 = on. Saved.",
    },
    {
        "name": "GETWINDENABLE",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Aktivstatus Windauswertung lesen. 0 = aus, 1 = ein.",
        "help_text_en": "Read wind evaluation active status. 0 = off, 1 = on.",
    },
    {
        "name": "GETANEMO",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Windgeschwindigkeit vom Windmesser in km/h. 0..200 km/h, 1 Nachkommastelle, inkl. Offset.",
        "help_text_en": "Wind speed from anemometer in km/h. 0..200 km/h, 1 decimal place, including offset.",
    },
    {
        "name": "GETBEAUFORT",
        "kind": "none",
        "params_literal": "0",
        "help_text": (
            "Windstärke als Beaufortwert (0–12). Liest die aktuelle Windstärke vom RS485-Wind-/Richtungssensor. "
            "0 = Windstille oder deaktivierter Sensor. Bei deaktiviertem Sensor oder ohne Hardware: NAK (NOWIND/NOHW). "
            'Ideal für Anzeige wie „ruhig", „frisch" oder „stark" ohne km/h-Umrechnung.'
        ),
        "help_text_en": (
            "Wind strength as Beaufort value (0–12). Reads current wind strength from RS485 wind/direction sensor. "
            "0 = calm or disabled sensor. Without hardware or disabled: NAK (NOWIND/NOHW). "
            'Ideal for display like "calm", "fresh" or "strong" without km/h conversion.'
        ),
    },
    {
        "name": "SETWINDDIROF",
        "kind": "float",
        "min_value": -360.0,
        "max_value": 360.0,
        "decimals": 1,
        "step": 0.1,
        "default": 0.0,
        "help_text": "Windrichtungs-Offset (Grad) setzen. Wird gespeichert und sofort angewendet.",
        "help_text_en": "Set wind direction offset (degrees). Saved and applied immediately.",
    },
    {
        "name": "GETWINDDIROF",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Richtungs-Offset in Grad lesen (1 Nachkommastelle, z.B. -12,3). Wert stammt aus NVS/Preferences Key wdo.",
        "help_text_en": "Read direction offset in degrees (1 decimal place, e.g. -12.3). Value from NVS/Preferences key wdo.",
    },
    {
        "name": "GETWINDDIR",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Errechnete Windrichtung in Grad lesen (0..359,9). Aus Lastprofil-Auswertung.",
        "help_text_en": "Read calculated wind direction in degrees (0..359.9). From load profile evaluation.",
    },
    {
        "name": "SETTEMPA",
        "kind": "int",
        "min_value": -40.0,
        "max_value": 125.0,
        "decimals": 0,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Warnschwelle Umgebungstemperatur setzen. Wert in °C. <=0 deaktiviert Warnung.",
        "help_text_en": "Set ambient temperature warning threshold. Value in °C. <=0 disables warning.",
    },
    {
        "name": "SETTEMPM",
        "kind": "int",
        "min_value": -40.0,
        "max_value": 125.0,
        "decimals": 0,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Warnschwelle Motortemperatur setzen. Wert in °C. <=0 deaktiviert Warnung.",
        "help_text_en": "Set motor temperature warning threshold. Value in °C. <=0 disables warning.",
    },
    {
        "name": "GETTEMPAW",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Warnschwelle Umgebungstemperatur (°C) lesen. <=0 deaktiviert die Warnung.",
        "help_text_en": "Read ambient temperature warning threshold (°C). <=0 disables the warning.",
    },
    {
        "name": "GETTEMPMW",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Warnschwelle Motortemperatur (°C) lesen. <=0 deaktiviert die Warnung.",
        "help_text_en": "Read motor temperature warning threshold (°C). <=0 disables the warning.",
    },
    {
        "name": "GETSWAPTMP",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Zuordnung Temperaturfühler lesen. 0 = normal, 1 = vertauscht.",
        "help_text_en": "Read temperature sensor assignment. 0 = normal, 1 = swapped.",
    },
    {
        "name": "SETSWAPTEMP",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 1.0,
        "decimals": 0,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Zuordnung Temperaturfühler setzen. 0 = normal, 1 = vertauscht. Wird gespeichert.",
        "help_text_en": "Set temperature sensor assignment. 0 = normal, 1 = swapped. Saved.",
    },
    {
        "name": "SETCOLDT",
        "kind": "int",
        "min_value": -40.0,
        "max_value": 50.0,
        "decimals": 0,
        "step": 1.0,
        "default": 5.0,
        "help_text": "Kälte-Schwelle (°C) setzen. Unterhalb: Extra-Reibung erlaubt.",
        "help_text_en": "Set cold threshold (°C). Below this: extra friction allowed.",
    },
    {
        "name": "GETCOLDT",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Kälte-Schwelle (°C) lesen. Unterhalb: Extra-Reibung erlaubt.",
        "help_text_en": "Read cold threshold (°C). Below this: extra friction allowed.",
    },
    {
        "name": "SETCOLDP",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 10.0,
        "help_text": "Extra-Reibung bei Kälte (%) setzen. Empf.: 10..25.",
        "help_text_en": "Set extra friction at cold (%). Rec.: 10..25.",
    },
    {
        "name": "GETCOLDP",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Extra-Reibung bei Kälte (%) lesen. Erlaubter Zuschlag.",
        "help_text_en": "Read extra friction at cold (%). Allowed addition.",
    },
    {
        "name": "SETCALIGNDG",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 90.0,
        "decimals": 0,
        "step": 1.0,
        "default": 10.0,
        "help_text": "Kalibrierung: Rampenbereich (Grad) setzen, der ignoriert wird. Empf.: 10 (Test) oder 30 (robust).",
        "help_text_en": "Calibration: set ramp range (degrees) to ignore. Rec.: 10 (test) or 30 (robust).",
    },
    {
        "name": "GETCALIGNDG",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Kalibrierung: Rampenbereich (Grad) lesen, der ignoriert wird.",
        "help_text_en": "Calibration: read ramp range (degrees) to ignore.",
    },
    {
        "name": "SETSTATMINDG",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 0,
        "step": 1.0,
        "default": 60.0,
        "help_text": "Statistik: Mindestbewegung (°) setzen. Nur Bewegungen > Wert zählen. Empf.: 30..90.",
        "help_text_en": "Statistics: set minimum movement (°). Only movements > value count. Rec.: 30..90.",
    },
    {
        "name": "GETSTATMINDG",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Statistik: Mindestbewegung (°) lesen. Nur große Fahrten zählen.",
        "help_text_en": "Statistics: read minimum movement (°). Only large moves count.",
    },
    {
        "name": "SETDRAG",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 200.0,
        "decimals": 0,
        "step": 1.0,
        "default": 25.0,
        "help_text": 'Schwellwert „mehr Reibung" (%) setzen. Mittelwert für Lastprofil. Empf.: 15..30.',
        "help_text_en": 'Set "more friction" threshold (%). Mean for load profile. Rec.: 15..30.',
    },
    {
        "name": "GETDRAG",
        "kind": "none",
        "params_literal": "0",
        "help_text": 'Schwellwert „mehr Reibung" (%) lesen. Mittelwert-Schwellwert.',
        "help_text_en": 'Read "more friction" threshold (%). Mean value threshold.',
    },
    {
        "name": "SETDRAGBINS",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 30.0,
        "help_text": "Anteil Bins über Schwellwert (%) setzen. Empf.: 30..70.",
        "help_text_en": "Set proportion of bins above threshold (%). Rec.: 30..70.",
    },
    {
        "name": "GETDRAGBINS",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Anteil Bins über Schwellwert (%) lesen. Wie viele Winkel-Bins müssen drüber sein.",
        "help_text_en": "Read proportion of bins above threshold (%). How many angle bins must be above.",
    },
    {
        "name": "SETDRAGPERSIST",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 50.0,
        "decimals": 0,
        "step": 1.0,
        "default": 3.0,
        "help_text": "Persistenz (Anzahl Fahrten) setzen. Wie oft hintereinander. Empf.: 3..5.",
        "help_text_en": "Set persistence (number of moves). How many times in a row. Rec.: 3..5.",
    },
    {
        "name": "GETDRAGPERSIST",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Persistenz (Anzahl Fahrten) lesen. Wie viele große Fahrten hintereinander nötig.",
        "help_text_en": "Read persistence (number of moves). How many large moves in a row needed.",
    },
    {
        "name": "SETWINDPEAK",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 200.0,
        "decimals": 0,
        "step": 1.0,
        "default": 60.0,
        "help_text": "Wind: Peak-Schwellwert (%) setzen. Für Böen. Empf.: 25..60.",
        "help_text_en": "Wind: set peak threshold (%). For gusts. Rec.: 25..60.",
    },
    {
        "name": "GETWINDPEAK",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Wind: Peak-Schwellwert (%) lesen. Für Böen/kurzzeitig hohe Last.",
        "help_text_en": "Wind: read peak threshold (%). For gusts/short high load.",
    },
    {
        "name": "SETWINDCOH",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 55.0,
        "help_text": 'Wind: Mindest-Kohärenz (%) setzen. Wie „gerichtet" die Last sein muss. Empf.: 50..70.',
        "help_text_en": 'Wind: set minimum coherence (%). How "directed" the load must be. Rec.: 50..70.',
    },
    {
        "name": "GETWINDCOH",
        "kind": "none",
        "params_literal": "0",
        "help_text": 'Wind: Mindest-Kohärenz (%) lesen. Wie „gerichtet" die Last sein muss.',
        "help_text_en": 'Wind: read minimum coherence (%). How "directed" the load must be.',
    },
    {
        "name": "GETCALVALID",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Gültige Kalibrierung gespeichert? 0 = nein, 1 = ja.",
        "help_text_en": "Valid calibration saved? 0 = no, 1 = yes.",
    },
    {
        "name": "SETCAL",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Kalibrierfahrt starten (0→360→0), Stromprofil lernen. Nur wenn referenziert (REFF).",
        "help_text_en": "Start calibration run (0→360→0), learn current profile. Only when homed (REFF).",
    },
    {
        "name": "ABORTCAL",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Kalibrierfahrt abbrechen. Stoppt Kalibrierung, Daten bleiben.",
        "help_text_en": "Abort calibration run. Stops calibration, data remains.",
    },
    {
        "name": "DELCAL",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Gespeicherte Kalibrierung löschen. Danach GETCALVALID=0.",
        "help_text_en": "Delete saved calibration. After this GETCALVALID=0.",
    },
    {
        "name": "CLRSTAT",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Live-Statistik löschen. Gut vor Tests, damit nur aktuelle Fahrten zählen.",
        "help_text_en": "Clear live statistics. Good before tests so only current moves count.",
    },
    {
        "name": "GETCALSTATE",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Status Kalibrierfahrt. Antwort: state;progress. state: 0=IDLE,1=RUNNING,2=DONE,3=ABORT.",
        "help_text_en": "Calibration run status. Response: state;progress. state: 0=IDLE,1=RUNNING,2=DONE,3=ABORT.",
    },
    {
        "name": "GETLOADSTAT",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Last-Statistik. Antwort: mean%;peak%;coh%;moves. Delta zur Kalibrierung.",
        "help_text_en": "Load statistics. Response: mean%;peak%;coh%;moves. Delta from calibration.",
    },
    {
        "name": "GETWIND",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Wind-Schätzung aus Motorlastprofil. Antwort: peak%;coh%;dirDeg;peakDeg.",
        "help_text_en": "Wind estimate from motor load profile. Response: peak%;coh%;dirDeg;peakDeg.",
    },
    {
        "name": "GETCALBINS",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Kalibrier-Bins lesen (72 Bins). Params: dir;start;count.",
        "help_text_en": "Read calibration bins (72 bins). Params: dir;start;count.",
    },
    {
        "name": "GETLIVEBINS",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Live-Bins lesen (72 Bins). Wie GETCALBINS, aktuelle Betriebsdaten.",
        "help_text_en": "Read live bins (72 bins). Like GETCALBINS, current operating data.",
    },
    {
        "name": "GETACCBINS",
        "kind": "none",
        "params_literal": "1;0;12",
        "help_text": "Schnelle aktuelle Last-Statistik (72 Bins). Params: DIR;START;COUNT. Reagiert schneller als GETLIVEBINS. Funktioniert auch ohne Kalibrierung.",
        "help_text_en": "Fast current load statistics (72 bins). Params: DIR;START;COUNT. Responds faster than GETLIVEBINS. Works without calibration.",
    },
    {
        "name": "SETACCBINSRST",
        "kind": "none",
        "params_literal": "1",
        "help_text": "ACC-Bin-Statistik zurücksetzen. Nur die schnelle ACC-Statistik wird gelöscht, nicht LIVE oder Kalibrierung.",
        "help_text_en": "Reset ACC bin statistics. Only the fast ACC statistics are cleared, not LIVE or calibration.",
    },
    {
        "name": "GETDELTABINS",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Delta-Bins (Live minus Cal) in % lesen. Werte können negativ sein.",
        "help_text_en": "Read delta bins (live minus cal) in %. Values can be negative.",
    },
    {
        "name": "GETWARN",
        "kind": "none",
        "params_literal": "0",
        "help_text": 'Warnungen abfragen. Antwort: "0" oder "id;id;..." (mehrere möglich).',
        "help_text_en": 'Query warnings. Response: "0" or "id;id;..." (multiple possible).',
    },
    {
        "name": "DELWARN",
        "kind": "none",
        "params_literal": "1",
        "help_text": "Warnungen löschen. Antwort ACK_DELWARN:1",
        "help_text_en": "Delete warnings. Response ACK_DELWARN:1",
    },
    {
        "name": "GETERR",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Aktuellen Fehlercode abfragen. Antwort ACK_ERR mit Code oder 0.",
        "help_text_en": "Query current error code. Response ACK_ERR with code or 0.",
    },
    {
        "name": "SETREF",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 1.0,
        "decimals": 0,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Homing (1) oder Fehler quittieren (0). Während die GUI einen Fehler zeigt, reicht SETREF oft nicht – Rotor prüfen, Meldung schließen, App neu starten. Warnungen: DELWARN.",
        "help_text_en": "Homing (1) or acknowledge fault (0). While the app shows an error, SETREF often is not enough – check rotor, close message, restart app. Warnings: DELWARN.",
    },
    {
        "name": "JOG",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Manuelles Verfahren (aktuell deaktiviert).",
        "help_text_en": "Manual movement (currently disabled).",
    },
    {
        "name": "SETPOSDG",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 2,
        "step": 0.01,
        "default": 0.0,
        "help_text": "Positionsfahrt in Grad starten. Zielwinkel z.B. 160,00. Bei kleinen Schritten ARRTOL evtl. größer wählen.",
        "help_text_en": "Start position move in degrees. Target angle e.g. 160.00. For small steps increase ARRTOL if needed.",
    },
    {
        "name": "SETPOSCC",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 2,
        "step": 0.01,
        "default": 0.0,
        "help_text": "Kompass-Soll AZ in Grad (Anzeige). Setzt nur den Sollzeiger, keine Positionsfahrt. Encoder-Panel kann wiederholt Winkel senden.",
        "help_text_en": "Compass AZ target in degrees (display only). Moves the target pointer only, no position move. Encoder panel may send angles repeatedly.",
    },
    {
        "name": "SETID",
        "kind": "int",
        "min_value": 1.0,
        "max_value": 254.0,
        "decimals": 0,
        "step": 1.0,
        "default": 20.0,
        "help_text": "Slave-Adresse setzen und speichern. Achtung: danach neue Adresse verwenden.",
        "help_text_en": "Set and save slave address. Note: use new address afterwards.",
    },
    {
        "name": "GETID",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Slave-Adresse lesen. Rückgabe 0..255.",
        "help_text_en": "Read slave address. Return value 0..255.",
    },
    {
        "name": "SETBEGINDG",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 2,
        "step": 0.01,
        "default": 0.0,
        "help_text": "Min-Winkel (Achsenanfang) setzen. Typisch 0,00.",
        "help_text_en": "Set minimum angle (axis start). Typically 0.00.",
    },
    {
        "name": "GETBEGINDG",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Min-Winkel (Achsenanfang) lesen. In 0,01°.",
        "help_text_en": "Read minimum angle (axis start). In 0.01°.",
    },
    {
        "name": "SETMAXDG",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 2,
        "step": 0.01,
        "default": 360.0,
        "help_text": "Max-Winkel setzen. Typisch 360,00.",
        "help_text_en": "Set maximum angle. Typically 360.00.",
    },
    {
        "name": "GETMAXDG",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Max-Winkel lesen. In 0,01°.",
        "help_text_en": "Read maximum angle. In 0.01°.",
    },
    {
        "name": "SETDGOFFSET",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 30.0,
        "decimals": 2,
        "step": 0.01,
        "default": 2.5,
        "help_text": "Offset (Grad) setzen. Wird bei Ausgabe/Regelung abgezogen. Typisch 2,25 oder 2,50.",
        "help_text_en": "Set offset (degrees). Subtracted during output/control. Typically 2.25 or 2.50.",
    },
    {
        "name": "GETDGOFFSET",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Offset (Grad) lesen. Wird bei Positionsausgabe abgezogen.",
        "help_text_en": "Read offset (degrees). Subtracted during position output.",
    },
    {
        "name": "SETANTOFF1",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 1,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Antennen-Versatz 1 setzen (0–360°). Pro Achse (AZ/EL) separat.",
        "help_text_en": "Set antenna offset 1 (0–360°). Separate per axis (AZ/EL).",
    },
    {
        "name": "GETANTOFF1",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Antennen-Versatz 1 lesen (Grad).",
        "help_text_en": "Read antenna offset 1 (degrees).",
    },
    {
        "name": "SETANTOFF2",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 1,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Antennen-Versatz 2 setzen (0–360°). Pro Achse (AZ/EL) separat.",
        "help_text_en": "Set antenna offset 2 (0–360°). Separate per axis (AZ/EL).",
    },
    {
        "name": "GETANTOFF2",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Antennen-Versatz 2 lesen (Grad).",
        "help_text_en": "Read antenna offset 2 (degrees).",
    },
    {
        "name": "SETANTOFF3",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 1,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Antennen-Versatz 3 setzen (0–360°). Pro Achse (AZ/EL) separat.",
        "help_text_en": "Set antenna offset 3 (0–360°). Separate per axis (AZ/EL).",
    },
    {
        "name": "GETANTOFF3",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Antennen-Versatz 3 lesen (Grad).",
        "help_text_en": "Read antenna offset 3 (degrees).",
    },
    {
        "name": "SETANGLE1",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 1,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Antennen-Öffnungswinkel 1 setzen (0–360°). Wird im Rotor gespeichert.",
        "help_text_en": "Set antenna beam width 1 (0–360°). Saved in rotor.",
    },
    {
        "name": "GETANGLE1",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Antennen-Öffnungswinkel 1 lesen (Grad).",
        "help_text_en": "Read antenna beam width 1 (degrees).",
    },
    {
        "name": "SETANGLE2",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 1,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Antennen-Öffnungswinkel 2 setzen (0–360°). Wird im Rotor gespeichert.",
        "help_text_en": "Set antenna beam width 2 (0–360°). Saved in rotor.",
    },
    {
        "name": "GETANGLE2",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Antennen-Öffnungswinkel 2 lesen (Grad).",
        "help_text_en": "Read antenna beam width 2 (degrees).",
    },
    {
        "name": "SETANGLE3",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 360.0,
        "decimals": 1,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Antennen-Öffnungswinkel 3 setzen (0–360°). Wird im Rotor gespeichert.",
        "help_text_en": "Set antenna beam width 3 (0–360°). Saved in rotor.",
    },
    {
        "name": "GETANGLE3",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Antennen-Öffnungswinkel 3 lesen (Grad).",
        "help_text_en": "Read antenna beam width 3 (degrees).",
    },
    {
        "name": "SETHOMEPWM",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 100.0,
        "help_text": "Homing: Max-PWM (%) setzen. Schnelle Homing-PWM. Empf.: 60..100.",
        "help_text_en": "Homing: set max PWM (%). Fast homing PWM. Rec.: 60..100.",
    },
    {
        "name": "GETHOMEPWM",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Homing: Max-PWM (%) lesen. Schnelle Homing-PWM.",
        "help_text_en": "Homing: read max PWM (%). Fast homing PWM.",
    },
    {
        "name": "SETHOMEBACKOFF",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 22.0,
        "help_text": "Homing: Rückzug (Grad) setzen. Wie weit nach Endschalter wegfahren. Empf.: 10..60.",
        "help_text_en": "Homing: set backoff (degrees). How far to move after limit switch. Rec.: 10..60.",
    },
    {
        "name": "GETHOMEBACKOFF",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Homing: Rückzug (Grad) lesen. Wie weit nach Endschalter wegfahren.",
        "help_text_en": "Homing: read backoff (degrees). How far to move after limit switch.",
    },
    {
        "name": "SETHOMERETURN",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 1.0,
        "decimals": 0,
        "step": 1.0,
        "default": 1.0,
        "help_text": "Rückfahrt auf 0 nach Homing setzen. 1=ja, 0=nein. Meist 1.",
        "help_text_en": "Set return to 0 after homing. 1=yes, 0=no. Usually 1.",
    },
    {
        "name": "GETHOMRETURN",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Rückfahrt auf 0 nach Homing lesen. 1=ja, 0=nein.",
        "help_text_en": "Read return to 0 after homing. 1=yes, 0=no.",
    },
    {
        "name": "SETHOMETIMEOUT",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 600000.0,
        "decimals": 0,
        "step": 100.0,
        "default": 120000.0,
        "help_text": "Homing: Timeout (ms) setzen. Wenn Homing abbricht: erhöhen. Empf.: 60000..120000.",
        "help_text_en": "Homing: set timeout (ms). If homing aborts: increase. Rec.: 60000..120000.",
    },
    {
        "name": "GETHOMETIMEOUT",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Homing: Timeout (ms) lesen. Empf.: 60000..120000.",
        "help_text_en": "Homing: read timeout (ms). Rec.: 60000..120000.",
    },
    {
        "name": "SETPOSTIMEOUT",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 600000.0,
        "decimals": 0,
        "step": 100.0,
        "default": 60000.0,
        "help_text": "Positions-Timeout (ms) setzen. Max. Zeit für Positionsfahrt. Empf.: 30000..90000.",
        "help_text_en": "Set position timeout (ms). Max. time for position move. Rec.: 30000..90000.",
    },
    {
        "name": "GETPOSTIMEOUT",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Positions-Timeout (ms) lesen. Max. Zeit für eine Positionsfahrt.",
        "help_text_en": "Read position timeout (ms). Max. time for a position move.",
    },
    {
        "name": "SETHANDSPEED",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 25.0,
        "help_text": "Handspeed (%) setzen. Sicher langsames Verfahren. Empf.: 10..40.",
        "help_text_en": "Set hand speed (%). Safe slow movement. Rec.: 10..40.",
    },
    {
        "name": "GETHANDSPEED",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Handspeed (%) lesen. Sicher langsames Verfahren (lokal/Service).",
        "help_text_en": "Read hand speed (%). Safe slow movement (local/service).",
    },
    {
        "name": "SETDEADMAN",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 2147483647.0,
        "decimals": 0,
        "step": 1000.0,
        "default": 0.0,
        "help_text": "Deadman/Keepalive Timeout (ms) setzen. 0=aus. Empf.: 2000..5000 wenn Master regelmäßig sendet.",
        "help_text_en": "Set deadman/keepalive timeout (ms). 0=off. Rec.: 2000..5000 if master sends regularly.",
    },
    {
        "name": "GETDEADMAN",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Deadman/Keepalive Timeout (ms) lesen. 0 = aus.",
        "help_text_en": "Read deadman/keepalive timeout (ms). 0 = off.",
    },
    {
        "name": "SETIWARN",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 2147483647.0,
        "decimals": 0,
        "step": 1000.0,
        "default": 250.0,
        "help_text": "Strom-Warnschwelle (mV) setzen. Nur Warnung, kein Stop. Empf.: 200..350.",
        "help_text_en": "Set current warning threshold (mV). Warning only, no stop. Rec.: 200..350.",
    },
    {
        "name": "GETIWARN",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Strom-Warnschwelle (mV) lesen. Nur Warnung, kein Stop.",
        "help_text_en": "Read current warning threshold (mV). Warning only, no stop.",
    },
    {
        "name": "SETIMAX",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 2147483647.0,
        "decimals": 0,
        "step": 1000.0,
        "default": 350.0,
        "help_text": "Strom-Abschaltschwelle (mV) setzen. Führt zu Stop + Fehler. Empf.: 300..600.",
        "help_text_en": "Set current shutdown threshold (mV). Leads to stop + error. Rec.: 300..600.",
    },
    {
        "name": "GETIMAX",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Strom-Abschaltschwelle (mV) lesen. Führt zu Stop + Fehler.",
        "help_text_en": "Read current shutdown threshold (mV). Leads to stop + error.",
    },
    {
        "name": "SETARRTOL",
        "kind": "float",
        "min_value": 0.0,
        "max_value": 5.0,
        "decimals": 2,
        "step": 0.01,
        "default": 0.02,
        "help_text": "Ankunftstoleranz (Grad) setzen. Wie nah ans Ziel. Empf.: 0,02..0,20.",
        "help_text_en": "Set arrival tolerance (degrees). How close to target. Rec.: 0.02..0.20.",
    },
    {
        "name": "GETARRTOL",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Ankunftstoleranz (Grad) lesen. Wie nah ans Ziel.",
        "help_text_en": "Read arrival tolerance (degrees). How close to target.",
    },
    {
        "name": "SETRAMP",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 180.0,
        "decimals": 0,
        "step": 1.0,
        "default": 30.0,
        "help_text": "Rampenlänge (Grad) setzen. Beschleunigen/Abbremsen über diesen Winkel. Empf.: 10..40.",
        "help_text_en": "Set ramp length (degrees). Accelerate/decelerate over this angle. Rec.: 10..40.",
    },
    {
        "name": "GETRAMP",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Rampenlänge (Grad) lesen. Beschleunigen/Abbremsen über diesen Winkel.",
        "help_text_en": "Read ramp length (degrees). Accelerate/decelerate over this angle.",
    },
    {
        "name": "SETMINPWM",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 25.0,
        "help_text": "Min-PWM (%) setzen. Untergrenze für Bewegung. Empf.: 20..35. Bei Stand: MINPWM hoch.",
        "help_text_en": "Set min PWM (%). Lower limit for movement. Rec.: 20..35. If stalling: increase MINPWM.",
    },
    {
        "name": "GETMINPWM",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Min-PWM (%) lesen. Untergrenze für Bewegung.",
        "help_text_en": "Read min PWM (%). Lower limit for movement.",
    },
    {
        "name": "SETSTALLTIMEOUT",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 10000.0,
        "decimals": 0,
        "step": 10.0,
        "default": 2000.0,
        "help_text": "Stall-Timeout (ms) setzen. Zeit bis SE_STALL. Empf.: 1500..4000. Bei ERR16: erhöhen.",
        "help_text_en": "Set stall timeout (ms). Time until SE_STALL. Rec.: 1500..4000. If ERR16: increase.",
    },
    {
        "name": "GETSTALLTIMEOUT",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Stall-Timeout (ms) lesen. Zeit, bis SE_STALL auslöst.",
        "help_text_en": "Read stall timeout (ms). Time until SE_STALL triggers.",
    },
    {
        "name": "SETMAXPWM",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 100.0,
        "help_text": "Max-PWM (%) dauerhaft setzen. Globales Limit für Positionsfahrt. Empf.: 60..100.",
        "help_text_en": "Set max PWM (%) permanently. Global limit for position move. Rec.: 60..100.",
    },
    {
        "name": "GETMAXPWM",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Max-PWM (%) lesen. Globales Limit für Positionsfahrt.",
        "help_text_en": "Read max PWM (%). Global limit for position move.",
    },
    {
        "name": "SETPWM",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 100.0,
        "help_text": "PWM-Limit (%) zur Laufzeit setzen. Ohne Speichern. Gut für Tests/Debug.",
        "help_text_en": "Set PWM limit (%) at runtime. Without saving. Good for tests/debug.",
    },
    {
        "name": "GETPWM",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Aktuell freigegebenes PWM-Limit (%) lesen. Kann durch SETMAXPWM/SETPWM beeinflusst sein.",
        "help_text_en": "Read currently enabled PWM limit (%). Can be influenced by SETMAXPWM/SETPWM.",
    },
    {
        "name": "RESET",
        "kind": "none",
        "params_literal": "1",
        "help_text": "Alles auf Auslieferungszustand zurücksetzen (Factory-Reset) und neu starten. Alle Einstellungen gehen verloren.",
        "help_text_en": "Reset everything to factory defaults and restart. All settings will be lost.",
    },
    {
        "name": "SETSTALLEN",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 1.0,
        "decimals": 0,
        "step": 1.0,
        "default": 1.0,
        "help_text": "Stall-Erkennung aktivieren (1) oder deaktivieren (0). 0 = aus, 1 = ein.",
        "help_text_en": "Enable (1) or disable (0) stall detection. 0 = off, 1 = on.",
    },
    {
        "name": "GETSTALLEN",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Stall-Erkennung lesen. 0 = aus, 1 = ein.",
        "help_text_en": "Read stall detection. 0 = off, 1 = on.",
    },
    {
        "name": "SETMINSTALLPWM",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 25.0,
        "help_text": "Mindest-PWM für Stall-Erkennung setzen. Verhindert Stall bei sehr kleiner PWM.",
        "help_text_en": "Set minimum PWM for stall detection. Prevents stall at very low PWM.",
    },
    {
        "name": "GETMINSTALLPWM",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Mindest-PWM für Stall-Erkennung lesen. Ab dieser PWM wird Stall geprüft.",
        "help_text_en": "Read minimum PWM for stall detection. Stall is checked from this PWM.",
    },
    {
        "name": "SETSTALLMINCOUNTS",
        "kind": "int",
        "min_value": 1.0,
        "max_value": 2147483647.0,
        "decimals": 0,
        "step": 1000.0,
        "default": 10.0,
        "help_text": "Mindestanzahl Encoder-Counts im Stall-Zeitfenster setzen. Plausibilität: PWM an, kaum Bewegung.",
        "help_text_en": "Set minimum encoder counts in stall time window. Plausibility: PWM on, little movement.",
    },
    {
        "name": "GETSTALLMINCOUNTS",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Mindestanzahl Encoder-Counts im Stall-Zeitfenster lesen.",
        "help_text_en": "Read minimum encoder counts in stall time window.",
    },
    {
        "name": "SETISFILTERLEN",
        "kind": "int",
        "min_value": 1.0,
        "max_value": 32.0,
        "decimals": 0,
        "step": 1.0,
        "default": 16.0,
        "help_text": "Strom-Mittelwertfilter Länge setzen. Größer = ruhiger, langsamer. Empf.: 1..32.",
        "help_text_en": "Set current averaging filter length. Larger = smoother, slower. Rec.: 1..32.",
    },
    {
        "name": "GETFILTERLEN",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Länge Strom-Mittelwertfilter lesen. Gehört zu SETISFILTERLEN.",
        "help_text_en": "Read current averaging filter length. Belongs to SETISFILTERLEN.",
    },
    {
        "name": "SETISHOLDMS",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 60000.0,
        "decimals": 0,
        "step": 10.0,
        "default": 60.0,
        "help_text": "Hold-Zeit Strom-Hardlimit (ms) setzen. HardStop muss so lange überschritten sein.",
        "help_text_en": "Set current hard limit hold time (ms). Hard stop must be exceeded for this long.",
    },
    {
        "name": "GETISHOLDMS",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Hold-Zeit Strom-Hardlimit (ms) lesen. Gehört zu SETISHOLDMS.",
        "help_text_en": "Read current hard limit hold time (ms). Belongs to SETISHOLDMS.",
    },
    {
        "name": "SETISGRACEMS",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 60000.0,
        "decimals": 0,
        "step": 10.0,
        "default": 200.0,
        "help_text": "Grace-Zeit Stromschutz (ms) setzen. Schonzeit nach Start/Umkehr: HardStop ignoriert.",
        "help_text_en": "Set current protection grace time (ms). Grace period after start/reverse: hard stop ignored.",
    },
    {
        "name": "GETGRACEMS",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Grace-Zeit Stromschutz (ms) lesen. Gehört zu SETISGRACEMS.",
        "help_text_en": "Read current protection grace time (ms). Belongs to SETISGRACEMS.",
    },
    {
        "name": "SETHOMESEEKPPWM",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 60.0,
        "help_text": "Zusätzliche Such-PWM für Homing-Suchphase setzen. Ergänzt Homing-PWM in Suchphase.",
        "help_text_en": "Set additional search PWM for homing search phase. Supplements homing PWM in search phase.",
    },
    {
        "name": "GETHOMESEEKPPWM",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Zusätzliche Such-PWM für Homing-Suchphase lesen.",
        "help_text_en": "Read additional search PWM for homing search phase.",
    },
    {
        "name": "SETENCCRI",
        "kind": "int",
        "min_value": 1.0,
        "max_value": 2147483647.0,
        "decimals": 0,
        "step": 1000.0,
        "default": 160000.0,
        "help_text": "Counts pro 360° Ring-Encoder setzen. Typisch ca. 160000. Wird gespeichert.",
        "help_text_en": "Set counts per 360° ring encoder. Typically approx. 160000. Saved.",
    },
    {
        "name": "GETENCCRI",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Counts pro 360° Ring-Encoder lesen. Integer für Skalierung.",
        "help_text_en": "Read counts per 360° ring encoder. Integer for scaling.",
    },
    {
        "name": "SETENCCAX",
        "kind": "int",
        "min_value": 1.0,
        "max_value": 2147483647.0,
        "decimals": 0,
        "step": 1000.0,
        "default": 28600.0,
        "help_text": "Counts pro 360° Axis/Motor-Encoder setzen. Typisch ca. 50000. Wird gespeichert.",
        "help_text_en": "Set counts per 360° axis/motor encoder. Typically approx. 50000. Saved.",
    },
    {
        "name": "GETENCCAX",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Counts pro 360° Axis/Motor-Encoder lesen. Integer für Skalierung.",
        "help_text_en": "Read counts per 360° axis/motor encoder. Integer for scaling.",
    },
    {
        "name": "SETENCTYPE",
        "kind": "int",
        "min_value": 1.0,
        "max_value": 2.0,
        "decimals": 0,
        "step": 1.0,
        "default": 1.0,
        "help_text": "Encoder-Variante setzen. 1 = Axis/Motor, 2 = Ring. Nach Wechsel Counts/Homing prüfen.",
        "help_text_en": "Set encoder variant. 1 = Axis/Motor, 2 = Ring. Check counts/homing after change.",
    },
    {
        "name": "GETENCTYPE",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Encoder-Variante lesen. 1 = Axis, 2 = Ring.",
        "help_text_en": "Read encoder variant. 1 = Axis, 2 = Ring.",
    },
    # Controller-Oberfläche (HW-Display / Tasten)
    {
        "name": "SETCONTID",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 245.0,
        "decimals": 0,
        "step": 1.0,
        "default": 1.0,
        "help_text": "Controller-ID (0–245) auf dem Gerät setzen. Darf nicht die RS485-Master-ID dieser Bridge sein.",
        "help_text_en": "Set controller ID (0–245) on the device. Must not equal this bridge's RS485 master ID.",
    },
    {
        "name": "GETCONTID",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Controller-ID vom Gerät lesen.",
        "help_text_en": "Read controller ID from the device.",
    },
    {
        "name": "SETCONIDF",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 245.0,
        "decimals": 0,
        "step": 1.0,
        "default": 1.0,
        "help_text": "Broadcast (Ziel 255): neue Controller-ID setzen. Nur verwenden, wenn genau ein Controller am Bus hängt.",
        "help_text_en": "Broadcast (destination 255): set new controller ID. Use only when exactly one controller is on the bus.",
    },
    {
        "name": "SETCONANTNAME1",
        "kind": "none",
        "params_literal": "NAME",
        "help_text": "Anzeigename Antenne 1 auf dem Controller setzen (max. 9 Zeichen, ohne : # $).",
        "help_text_en": "Set antenna 1 display name on the controller (max 9 chars, no : # $).",
    },
    {
        "name": "GETCONANTNAME1",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Anzeigename Antenne 1 vom Controller lesen.",
        "help_text_en": "Read antenna 1 display name from the controller.",
    },
    {
        "name": "SETCONANTNAME2",
        "kind": "none",
        "params_literal": "NAME",
        "help_text": "Anzeigename Antenne 2 auf dem Controller setzen (max. 9 Zeichen).",
        "help_text_en": "Set antenna 2 display name on the controller (max 9 chars).",
    },
    {
        "name": "GETCONANTNAME2",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Anzeigename Antenne 2 vom Controller lesen.",
        "help_text_en": "Read antenna 2 display name from the controller.",
    },
    {
        "name": "SETCONANTNAME3",
        "kind": "none",
        "params_literal": "NAME",
        "help_text": "Anzeigename Antenne 3 auf dem Controller setzen (max. 9 Zeichen).",
        "help_text_en": "Set antenna 3 display name on the controller (max 9 chars).",
    },
    {
        "name": "GETCONANTNAME3",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Anzeigename Antenne 3 vom Controller lesen.",
        "help_text_en": "Read antenna 3 display name from the controller.",
    },
    {
        "name": "SETCONSPWM",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 30.0,
        "help_text": "PWM für Taste „Slow“ auf dem Controller setzen (0–100 %).",
        "help_text_en": "Set PWM for the Slow button on the controller (0–100 %).",
    },
    {
        "name": "GETCONSPWM",
        "kind": "none",
        "params_literal": "0",
        "help_text": "PWM für Taste „Slow“ vom Controller lesen.",
        "help_text_en": "Read PWM for the Slow button from the controller.",
    },
    {
        "name": "SETCONFPWM",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 80.0,
        "help_text": "PWM für Taste „Fast“ auf dem Controller setzen (0–100 %).",
        "help_text_en": "Set PWM for the Fast button on the controller (0–100 %).",
    },
    {
        "name": "GETCONFPWM",
        "kind": "none",
        "params_literal": "0",
        "help_text": "PWM für Taste „Fast“ vom Controller lesen.",
        "help_text_en": "Read PWM for the Fast button from the controller.",
    },
    {
        "name": "SETCONFRQ",
        "kind": "int",
        "min_value": 100.0,
        "max_value": 4000.0,
        "decimals": 0,
        "step": 1.0,
        "default": 1000.0,
        "help_text": "Piep-Tonhöhe (Frequenz in Hz) für den Lautsprecher am Controller (100–4000).",
        "help_text_en": "Beeper pitch (frequency in Hz) on the controller speaker (100–4000).",
    },
    {
        "name": "GETCONFRQ",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Piep-Frequenz (Hz) vom Controller lesen.",
        "help_text_en": "Read beep frequency (Hz) from the controller.",
    },
    {
        "name": "SETLSL",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 50.0,
        "decimals": 0,
        "step": 1.0,
        "default": 25.0,
        "help_text": "Lautstärke des Piepens am Lautsprecher (0–50).",
        "help_text_en": "Beeper volume on the controller speaker (0–50).",
    },
    {
        "name": "GETLSL",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Piep-Lautstärke vom Controller lesen.",
        "help_text_en": "Read beep volume from the controller.",
    },
    {
        "name": "SETCONLEDP",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 100.0,
        "decimals": 0,
        "step": 1.0,
        "default": 100.0,
        "help_text": "LED-Ring-Helligkeit am Controller in Prozent (0–100).",
        "help_text_en": "Controller LED ring brightness in percent (0–100).",
    },
    {
        "name": "GETCONLEDP",
        "kind": "none",
        "params_literal": "0",
        "help_text": "LED-Ring-Helligkeit (0–100 %) vom Controller lesen.",
        "help_text_en": "Read LED ring brightness (0–100 %) from the controller.",
    },
    {
        "name": "SETCONANO",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 1.0,
        "decimals": 0,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Windmesser am Controller ein (1) oder aus (0).",
        "help_text_en": "Enable (1) or disable (0) anemometer on the controller.",
    },
    {
        "name": "GETCONANO",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Windmesser-Status (0/1) vom Controller lesen.",
        "help_text_en": "Read anemometer enable state (0/1) from the controller.",
    },
    {
        "name": "SETCONDELTA",
        "kind": "int",
        "min_value": 1.0,
        "max_value": 10.0,
        "decimals": 0,
        "step": 1.0,
        "default": 10.0,
        "help_text": "Encoder-Schrittweite: 1 = 0,1°, 10 = 1°.",
        "help_text_en": "Encoder step: 1 = 0.1°, 10 = 1°.",
    },
    {
        "name": "GETCONDELTA",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Encoder-Schrittweite (1 oder 10) vom Controller lesen.",
        "help_text_en": "Read encoder step (1 or 10) from the controller.",
    },
    {
        "name": "SETCONCHA",
        "kind": "int",
        "min_value": 0.0,
        "max_value": 1.0,
        "decimals": 0,
        "step": 1.0,
        "default": 0.0,
        "help_text": "Beim Antennenwechsel: neue Antenne zur gleichen Peilung wie die vorherige fahren (1 = ein, 0 = aus).",
        "help_text_en": "On antenna change: move new antenna to same bearing as the previous (1 = on, 0 = off).",
    },
    {
        "name": "GETCONCHA",
        "kind": "none",
        "params_literal": "0",
        "help_text": "Nachdrehen beim Antennenwechsel (0/1) vom Controller lesen.",
        "help_text_en": "Read antenna realign-on-switch state (0/1) from the controller.",
    },
]


def command_specs() -> list[CommandSpec]:
    """Gibt die Liste der bekannten Commands sortiert (A–Z, SET vor GET) zurück."""
    specs: list[CommandSpec] = [CommandSpec(**d) for d in SPECS_DATA]

    def _split_base_and_kind(cmd_name: str) -> tuple[str, str]:
        if cmd_name.startswith("SET") and len(cmd_name) > 3:
            return cmd_name[3:], "SET"
        if cmd_name.startswith("GET") and len(cmd_name) > 3:
            return cmd_name[3:], "GET"
        if cmd_name.startswith("ABORT") and len(cmd_name) > 5:
            return cmd_name[5:], "ABORT"
        return cmd_name, "OTHER"

    def _order_in_group(kind: str) -> int:
        if kind == "SET":
            return 0
        if kind == "ABORT":
            return 1
        if kind == "GET":
            return 2
        return 3

    def _sort_key(spec: CommandSpec) -> tuple[str, int, str]:
        base, kind = _split_base_and_kind(spec.name)
        return (base.casefold(), _order_in_group(kind), spec.name.casefold())

    specs.sort(key=_sort_key)
    return specs


def format_cmd_tooltip(spec: CommandSpec) -> str:
    """Erzeugt einen Tooltip-Text (mehrzeilig) für einen CMD-Eintrag – sprachabhängig via i18n."""
    from .i18n import LANG_CODE, format_tooltip, t

    use_en = LANG_CODE == "en"
    i18n_key = f"catalog.help.{spec.name}"
    fallback = spec.help_text_en if use_en and spec.help_text_en else spec.help_text
    help_str = t(i18n_key, fallback=fallback)

    lines: list[str] = [spec.name]
    if help_str:
        lines.append(help_str)

    if spec.kind in ("int", "float"):
        if spec.min_value is not None and spec.max_value is not None:
            lines.append(f"{t('catalog.range')}: {spec.min_value} .. {spec.max_value}")
        if spec.default is not None:
            lines.append(f"{t('catalog.default')}: {spec.default}")
        if spec.step is not None:
            lines.append(f"{t('catalog.step')}: {spec.step}")
        if spec.kind == "float" and spec.decimals is not None:
            lines.append(f"{t('catalog.decimals')}: {spec.decimals}")

    return format_tooltip("\n".join(lines))
